<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np

Fit a line to data with a masked outlier in ``y``:


In [ ]:
x = np.ma.array([0., 1., 2., 3., 4.])
y = np.ma.array([1., 3., 5., 7., 999.], mask=[0, 0, 0, 0, 1])
np.ma.polyfit(x, y, 1)

array([2., 1.])

Masking a value in ``x`` also excludes the corresponding ``y`` point:


In [ ]:
x = np.ma.array([0., 1., 999., 3., 4.], mask=[0, 0, 1, 0, 0])
y = np.ma.array([1., 3., 5., 7., 9.])
np.ma.polyfit(x, y, 1)

array([2., 1.])

Without masking, an outlier distorts the fit significantly:


In [ ]:
np.polyfit([0., 1., 2., 3., 4.], [1., 3., 5., 7., 999.], 1)

array([ 200., -197.])