<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
a = np.arange(4).reshape(2, 2); a

array([[0, 1],
       [2, 3]])

In [ ]:
np.linalg.diagonal(a)

array([0, 3])

A 3-D example:


In [ ]:
a = np.arange(8).reshape(2, 2, 2); a

array([[[0, 1],
        [2, 3]],
       [[4, 5],
        [6, 7]]])

In [ ]:
np.linalg.diagonal(a)

array([[0, 3],
       [4, 7]])

Diagonals adjacent to the main diagonal can be obtained by using the
`offset` argument:


In [ ]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.linalg.diagonal(a, offset=1)  # First superdiagonal

array([1, 5])

In [ ]:
np.linalg.diagonal(a, offset=2)  # Second superdiagonal

array([2])

In [ ]:
np.linalg.diagonal(a, offset=-1)  # First subdiagonal

array([3, 7])

In [ ]:
np.linalg.diagonal(a, offset=-2)  # Second subdiagonal

array([6])

The anti-diagonal can be obtained by reversing the order of elements
using either `numpy.flipud` or `numpy.fliplr`.


In [ ]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.linalg.diagonal(np.fliplr(a))  # Horizontal flip

array([2, 4, 6])

In [ ]:
np.linalg.diagonal(np.flipud(a))  # Vertical flip

array([6, 4, 2])

Note that the order in which the diagonal is retrieved varies depending
on the flip function.