<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

It is equivalent to ``reshape(-1, order=order)``.


In [ ]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [ ]:
x.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.ravel(x, order='F')

array([1, 4, 2, 5, 3, 6])

When ``order`` is 'A', it will preserve the array's 'C' or 'F' ordering:


In [ ]:
np.ravel(x.T)

array([1, 4, 2, 5, 3, 6])

In [ ]:
np.ravel(x.T, order='A')

array([1, 2, 3, 4, 5, 6])

When ``order`` is 'K', it will preserve orderings that are neither 'C'
nor 'F', but won't reverse axes:


In [ ]:
a = np.arange(3)[::-1]; a

array([2, 1, 0])

In [ ]:
a.ravel(order='C')

array([2, 1, 0])

In [ ]:
a.ravel(order='K')

array([2, 1, 0])

In [ ]:
a = np.arange(12).reshape(2,3,2).swapaxes(1,2); a

array([[[ 0,  2,  4],
        [ 1,  3,  5]],
       [[ 6,  8, 10],
        [ 7,  9, 11]]])

In [ ]:
a.ravel(order='C')

array([ 0,  2,  4,  1,  3,  5,  6,  8, 10,  7,  9, 11])

In [ ]:
a.ravel(order='K')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])