<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

Set items 0 and 1 to their negative values:


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4])
np.negative.at(a, [0, 1])
a

array([-1, -2,  3,  4])

Increment items 0 and 1, and increment item 2 twice:


In [ ]:
a = np.array([1, 2, 3, 4])
np.add.at(a, [0, 1, 2, 2], 1)
a

array([2, 3, 5, 4])

Add items 0 and 1 in first array to second array,
and store results in first array:


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2])
np.add.at(a, [0, 1], b)
a

array([2, 4, 3, 4])