<div class='alert alert-warning'>

NumPy's interactive examples are experimental and may not always work as expected, with high load times especially on low-resource platforms, and the version of NumPy might not be in sync with the one you are browsing the documentation for. If you encounter any issues, please report them on the [NumPy issue tracker](https://github.com/numpy/numpy/issues).

</div>

In [ ]:
import numpy as np
np.correlate([1, 2, 3], [0, 1, 0.5])

array([3.5])

In [ ]:
np.correlate([1, 2, 3], [0, 1, 0.5], "same")

array([2. ,  3.5,  3. ])

In [ ]:
np.correlate([1, 2, 3], [0, 1, 0.5], "full")

array([0.5,  2. ,  3.5,  3. ,  0. ])

Using complex sequences:


In [ ]:
np.correlate([1+1j, 2, 3-1j], [0, 1, 0.5j], 'full')

array([ 0.5-0.5j,  1.0+0.j ,  1.5-1.5j,  3.0-1.j ,  0.0+0.j ])

Note that you get the time reversed, complex conjugated result
($\overline{c_{-k}}$) when the two input sequences a and v change
places:


In [ ]:
np.correlate([0, 1, 0.5j], [1+1j, 2, 3-1j], 'full')

array([ 0.0+0.j ,  3.0+1.j ,  1.5+1.5j,  1.0+0.j ,  0.5+0.5j])